# Setup
title:                 Sathvik Swaminathan
tagline:               ''
description:           ''
url:                   "https://sathvikswaminathan.github.io"
baseurl: ""            # Leave baseurl empty (no slash) for user/organization sites
paginate:              5
permalink:             pretty

# About/contact
author:
  name:                Sathvik Swaminathan
  url:                 https://www.linkedin.com/in/sathvik-swaminathan-50b424178/
  email:               sathvikswaminathan@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:               1.1.0
google_analytics_id:   #UA-XXXX-Y

# Excerpt separator
excerpt_separator: "<!--more-->"
